#*******************************************************************************
# 
#   Dockerfile_development:  dockerfile used to build the development image that
#         runs the online.interlisp.org web portal.  This image is basically 
#         just dev tools added to the production image for the portal
# 
#   2022-02-02 Frank Halasz
# 
# 
#   Copyright: 2022 by Interlisp.org 
# 
#
# *****************************************************************************/
ARG DOCKER_NAMESPACE=interlisp
ARG DOCKER_REGISTRY="ghcr.io/"

FROM ${DOCKER_REGISTRY}${DOCKER_NAMESPACE}/online-production:latest
SHELL ["/bin/bash", "-c"]
USER root:root
#
ARG DEBIAN_FRONTEND=noninteractive
#
#     The basics, git, ccrypt
#
# software-properties-common include apt-add-repository
RUN apt-get update \
    && apt-get install -y apt-utils software-properties-common build-essential \
    && apt-get install -y nano vim \
    && apt-get install -y git \
    && apt-get install -y ccrypt \
    && apt-get install -y gh
#
#  Repopulate the web-portal source code with full portal code base and .git directory
#
COPY --chown=oio:oio . /opt/oio
WORKDIR /opt/oio
# re-setup novnc
COPY --chown=oio:oio web-portal/client/novnc_oio/rfb.js                web-portal/client/novnc/core/rfb.js
COPY --chown=oio:oio web-portal/client/novnc_oio/vnc.html              web-portal/client/novnc/vnc.html
COPY --chown=oio:oio web-portal/client/novnc_oio/ui.js                 web-portal/client/novnc/app/ui.js
COPY --chown=oio:oio web-portal/client/novnc_oio/Interlisp-FavIcon-*   web-portal/client/novnc/app/images/icons
#
ENV DOCKER_NAMESPACE=${DOCKER_NAMESPACE}
WORKDIR /opt/oio
USER root
ENTRYPOINT /opt/oio/startup/entrypoint.sh
