#!/bin/bash
set -x
if [ $# -gt 0 ]; then
	width=$1
else
	width=1024
fi

if [ $# -gt 1 ]; then
	height=$2
else
	height=808
fi
#
export SFTP_PORT=2${PORT}
/usr/sbin/sshd -e -p ${SFTP_PORT}

export SFTP_PWD=$(date +%s | sha256sum | base64 | head -c 8)
echo medley:${SFTP_PWD} | chpasswd

/usr/bin/websockify --daemon --key ${TLS_KEYFILE} --cert ${TLS_CERTFILE} --ssl-only ${PORT} localhost:1${PORT}
/usr/bin/Xvnc -geometry ${width}x${height} -rfbport 1${PORT} -nolisten tcp -localhost -nevershared -dontdisconnect :0 &
export DISPLAY=:0
for i in {1..10}
    do
        xdpyinfo > /dev/null
        if [ $? -eq 0 ]; 
            then
                break
            else
                sleep 1
        fi
    done
xmodmap -e "keycode 12 = Alt_L" -e "keycode 13 = Alt_R" -e "keycode 14 = Meta_L" -e "keycode 15 = Meta_R"
/usr/bin/autocutsel -s CLIPBOARD &
su medley <<EOF
set -x
xrdb -merge /home/medley/.Xresources
(echo ".         Files are now available by SFTP to notecards.online using port 2${PORT}.  Username is 'medley'.  Password is ${SFTP_PWD}" | xmessage -file - -geometry ${width}x66+5+0)  &
twm &
sleep 1
export TMOUT=1800
/usr/bin/xterm -geometry 168x55+5+60
EOF

