#!/bin/bash
#
#    Call run-medley within an online.interlisp.org docker container.  But startup XVnc, websockify and sftpd first.
#    Expects $PORT to be set to the port to be used.  In actuality, ${PORT} will be used as websocket interface to XVnc,
#    1${PORT} will be used as the TCP interface to XVnc, and 2${PORT} will be used as the address of the sftp deamon.
#
#    2021-11-11 Frank Halasz
#
#set -x

RELEASE_SYSOUT_PATH="${MEDLEYDIR}/loadups/full.sysout"
SYSOUT_PATH="${MEDLEYDIR}/sysout/online.sysout"
VMEM_PATH="${MEDLEYDIR}/vmem/lisp.virtualmem"

if [ ! -e ${SYSOUT_PATH} ]; then
	/bin/cp -p ${RELEASE_SYSOUT_PATH} ${SYSOUT_PATH}
fi

if [ $# -gt 0 ]; then
	if [ "$1" == "sysout" ]; then
		sysout=${SYSOUT_PATH}
	else
		if [ -f ${VMEM_PATH} ]; then
			sysout=""
		else 
			sysout=${SYSOUT_PATH}
		fi
	fi
else
	sysout=${SYSOUT_PATH}
fi

if [ $# -gt 1 ]; then
	width=$2
else
	width=1024
fi

if [ $# -gt 2 ]; then
	height=$3
else
	height=808
fi

export SFTP_PORT=2${PORT}
/usr/sbin/sshd -e -p ${SFTP_PORT}

export SFTP_PWD=$(date +%s | sha256sum | base64 | head -c 8)
echo medley:${SFTP_PWD} | chpasswd
#
/usr/bin/websockify --daemon --key ${TLS_KEYFILE} --cert ${TLS_CERTFILE} --ssl-only ${PORT} localhost:1${PORT}
/usr/bin/Xvnc -geometry ${width}x${height} -rfbport 1${PORT} -nolisten tcp -localhost -nevershared -dontdisconnect :0 &
export DISPLAY=:0
for i in {1..10}
    do
        xdpyinfo > /dev/null
        if [ $? -eq 0 ]; 
            then
                break
            else
                sleep 1
        fi
    done
xmodmap -e "keycode 12 = Alt_L" -e "keycode 13 = Alt_R" -e "keycode 14 = Meta_L" -e "keycode 15 = Meta_R"
/usr/bin/autocutsel -s CLIPBOARD &
sleep 1
su medley <<EOF
#set -x
xrdb -merge /home/medley/.Xresources
cd ${MEDLEYDIR}
export LOGINDIR=${MEDLEYDIR}
MAIKODIR="/app/maiko" ./run-medley -noscroll -g ${width}x${height} -sc ${width}x${height} -vmem ${VMEM_PATH} ${sysout}
EOF
