#!/bin/bash
#
#    Call run-medley within an online.interlisp.org docker container.  But startup XVnc, websockify and sftpd first.
#    Expects $PORT to be set to the port to be used.  In actuality, ${PORT} will be used as websocket interface to XVnc,
#    1${PORT} will be used as the TCP interface to XVnc, and 2${PORT} will be used as the address of the sftp deamon.
#
#    2021-11-11 Frank Halasz
#
#    Copyright: 2022 by Interlisp.org
#
#
#set -x

TLS_CERT_FILE=/etc/letsencrypt/live/online.interlisp.org/fullchain.pem
TLS_KEY_FILE=/etc/letsencrypt/live/online.interlisp.org/privkey.pem

if [ -z "${NCO}" ]; then export NCO="false"; fi
if [ -z "${MEDLEY_EXEC}" ]; then export MEDLEY_EXEC="common"; fi
RELEASE_SYSOUT_PATH="${MEDLEY_INSTALLDIR}/loadups/apps.sysout"
CUSTOM_SYSOUT_PATH="${MEDLEY_USERDIR}/sysout/online.sysout"
RELEASE_INIT_PATH="${MEDLEY_INSTALLDIR}/greetfiles/ONLINE-INIT.LCOM"
CUSTOM_INIT_PATH="${MEDLEY_USERDIR}/initdir/ONLINE-INIT"

if [ "${NCO}" == "true" ];
   then VMEM_PATH="${MEDLEY_USERDIR}/vmem/notecards.virtualmem"
   else VMEM_PATH="${MEDLEY_USERDIR}/vmem/lisp.virtualmem"
fi

if [ -z "${MEDLEY_MEMORY}" ];
then
    medley_memory_arg=""
else
    medley_memory_arg="-m ${MEDLEY_MEMORY}"
fi

if [ $# -gt 0 ]; then
    case "$1" in
	    sysout)
	        sysout=${RELEASE_SYSOUT_PATH}
	        ;;
	    custom)
			if [ -f ${CUSTOM_SYSOUT_PATH} ]; then
				sysout=${CUSTOM_SYSOUT_PATH}
			else
				sysout=${RELEASE_SYSOUT_PATH}
			fi
			;;
	    vmem)
			if [ -f ${VMEM_PATH} ]; then
				sysout=""
			else
				sysout=${RELEASE_SYSOUT_PATH}
			fi
			;;
		*)
		    sysout=${RELEASE_SYSOUT_PATH}
		    ;;
    esac
else
	sysout=${RELEASE_SYSOUT_PATH}
fi
#
export MEDLEY_INIT_PATH="${RELEASE_INIT_PATH}"
if [ $# -gt 1 ] && [ "$2" = "custom" ]; then
    if [ -f "${CUSTOM_INIT_PATH}.LCOM" ]; then
         MEDLEY_INIT_PATH="${CUSTOM_INIT_PATH}.LCOM"
    elif [ -f "${CUSTOM_INIT_PATH}" ] ; then
         MEDLEY_INIT_PATH="${CUSTOM_INIT_PATH}"
    fi
fi
#
unset START_SCRIPT
if [ -n "${START_SCRIPT_URL}" ]
then
  export START_SCRIPT="${MEDLEY_USERDIR}/initdir/START-SCRIPT"
  mkdir -p "$(dirname "${START_SCRIPT}")"
  wget "${START_SCRIPT_URL}" -O "${START_SCRIPT}"
  if [ $? -ne 0 ]
  then
    rm -f "${START_SCRIPT}"
    unset START_SCRIPT
  fi
fi
unset START_SCRIPT_URL
#
if [ $# -gt 2 ]; then
	width=$3
else
	width=1024
fi
width=$(( ( $width / 32 ) * 32 ))
#
if [ $# -gt 3 ]; then
	height=$4
else
	height=808
fi
height=$(( ( $height / 32 ) * 32 ))
#
export SFTP_PORT=2${PORT}
if [ -z "${SFTP_SERVER}" ]; then
    export SFTP_SERVER="false";
fi
if [ "${SFTP_SERVER}" == "true" ]; then
    /usr/sbin/sshd -e -p ${SFTP_PORT}
fi
#
if [ -z "${SFTP_PWD}" ]; then
    export SFTP_PWD=$(date +%s | sha256sum | base64 | head -c 8);
fi
echo medley:${SFTP_PWD} | chpasswd
#

if [ ${SUPPORT_HTTPS} = "yes" ];
  then /usr/bin/websockify --daemon --key ${TLS_KEYFILE} --cert ${TLS_CERTFILE} --ssl-only ${PORT} localhost:1${PORT}
  else /usr/bin/websockify --daemon  ${PORT} localhost:1${PORT}
fi
/usr/bin/Xvnc -geometry ${width}x${height} -rfbport 1${PORT} -SecurityTypes None \
              -nolisten tcp -localhost -NeverShared -DisconnectClients=0 \
              -MaxIdleTime ${IDLE_SECS:=3600} \
              :${PORT} &
export DISPLAY=:${PORT}
for i in {1..10}
    do
        xdpyinfo > /dev/null
        if [ $? -eq 0 ];
            then
                break
            else
                sleep 1
        fi
    done
xmodmap -e "keysym Alt_R = Alt_L" -e "keysym Meta_R = Meta_L"
#xmodmap -e "keycode 12 = Alt_L" -e "keycode 13 = Alt_R" -e "keycode 14 = Meta_L" -e "keycode 15 = Meta_R"
/usr/bin/autocutsel -s CLIPBOARD &
sleep 1
if [ -z "${MEDLEY_UNAME}" ]; then
	export MEDLEY_UNAME=medley
fi
if [ "${MEDLEY_UNAME}" != "medley" ]; then
    usermod --login ${MEDLEY_UNAME} medley
fi

if [ "${NCO}" == "true" ]; then RUN_NOTECARDS="true"; fi
#
#
export FILEBROWSER_DATABASE=/usr/local/filebrowser/filebrowser.db
export FILEBROWSER_PORT=3${PORT}
if [ ${SUPPORT_HTTPS} = "yes" ];
then
  export FILEBROWSER_CERT="--cert ${TLS_CERT_FILE}"
  export FILEBROWSER_KEY="--key ${TLS_KEY_FILE}"
else
  export FILEBROWSER_CERT=""
  export FILEBROWSER_KEY=""
fi
/usr/local/bin/filebrowser users add "${MEDLEY_UNAME}" "${SFTP_PWD}" \
          -d ${FILEBROWSER_DATABASE} --lockPassword --perm.share=false --perm.execute=false
/usr/local/bin/filebrowser -d ${FILEBROWSER_DATABASE} --port ${FILEBROWSER_PORT} \
          ${FILEBROWSER_CERT} ${FILEBROWSER_KEY} &
export OIO_FB_URL="${OIO_FB_URL}:${FILEBROWSER_PORT}/files/il?u=${MEDLEY_UNAME}&p=${SFTP_PWD}"
#
#  Start http server
#
# need to create WEBDIR here (if needed) and not in Dockerfile_medley since file system might be remaining
# from before WEBDIR was intrduced
if [ ! -e "${MEDLEY_WEBDIR}" ]
then
    mkdir -p "${MEDLEY_WEBDIR}"
    chown ${MEDLEY_UNAME}:medley "${MEDLEY_WEBDIR}"
    cp -rp "${OIO_INSTALLDIR}"/misc/test.html  "${MEDLEY_WEBDIR}"
    chown ${MEDLEY_UNAME}:medley "${MEDLEY_WEBDIR}"/test.html
fi
HTTP_PORT=4${PORT}
if [ ${SUPPORT_HTTPS} = "yes" ]
then
   "${OIO_INSTALLDIR}"/bin/https.py \
        "${HTTP_PORT}" "${TLS_CERT_FILE}" "${TLS_KEY_FILE}" "${MEDLEY_WEBDIR}" &
else
  /usr/bin/python3 -m http.server ${HTTP_PORT} -d "${MEDLEY_WEBDIR}" &
fi
export OIO_WEBFILES_PORT=${HTTP_PORT}
#
#
#
su ${MEDLEY_UNAME} <<EOF
#set -x
xrdb -merge /home/medley/.Xresources
cd ${MEDLEY_INSTALLDIR}
export MEDLEY_ONLINE="true"
export MEDLEYDIR=${MEDLEY_INSTALLDIR}
export LOGINDIR=${MEDLEY_USERDIR}
export LDEINIT=${MEDLEY_INIT_PATH}
export MAIKODIR="/usr/local/interlisp/maiko"
./run-medley -noscroll ${medley_memory_arg} -g ${width}x${height} -sc ${width}x${height} -vmem ${VMEM_PATH} ${sysout}
EOF
